version: 2.1
dependencies:
  pre:
    - source environmentSetup.sh && copyEnvVarsToGradleProperties
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: ChmodPermssion
          command: sudo chmod +x code/gradlew  
      - run:
          name: Path
          command: pwd 
      - run:
          name: CircleCIBranch
          command: echo $CIRCLE_BRANCH 
            
      # - run:
      #     name: Echo
      #     command: cd $HOME/code && cd code && ls && echo "$(cat gradle.properties)"
      - run:
          name: ScriptRun 
          command: source environmentSetup.sh && copyEnvVarsToGradleProperties

      # - run:
      #     name: Javadoc
      #     command: code/gradlew -q -p code/places-monitor-android javadocPublic       
      # - run:
      #     name: Build
      #     command: code/gradlew -p code/places-monitor-android assemblePhoneCoreBundleDebug
      # - run:
      #     name: UnitTests
      #     command: code/gradlew -p code/places-monitor-android platformUnitTestJacocoReport
      - run:
          name: Artifactory Publish
          command: code/gradlew -p code/places-monitor-android artifactoryPublish
 